name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.x'  # Specify your .NET version here

    # Restore NuGet packages for all solutions
    - name: Restore NuGet packages
      run: |
        find . -name '*.sln' | while read solution; do
          dotnet restore "$solution"
        done

    # Build all solutions
    - name: Build solutions
      run: |
        find . -name '*.sln' | while read solution; do
          dotnet build "$solution" --configuration ${{ matrix.configuration }} --no-restore
        done

    # Publish all solutions
    - name: Publish solutions
      run: |
        find . -name '*.sln' | while read solution; do
          dotnet publish "$solution" --configuration ${{ matrix.configuration }} --no-restore --output ./publish/${{ matrix.configuration }}
        done

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-app-${{ matrix.configuration }}
        path: ./publish/${{ matrix.configuration }}
